spring.datasource.url=jdbc:mariadb://mewspaper-dev.cl8ygaiowfq8.ap-southeast-2.rds.amazonaws.com:3306/mewspaper?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8mb4&connectionCollation=utf8mb4_general_ci
spring.datasource.username=admin
spring.datasource.password=admin1234!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.pathmatch.matching-strategy=ant-path-matcher
server.port=8080

naver.client-id=msomrq9u6K2lHoauBLPb
naver.client-secret=PzHHOFVMS4
naver.callback-uri=http://localhost:5173/auth/naver/callback # 프론트엔드와 동일
naver.token-uri=https://nid.naver.com/oauth2.0/token
naver.profile-uri=https://openapi.naver.com/v1/nid/me

google.client-id=135264619251-cttudh1gaa0brlug34ii737kv5v4g5c8.apps.googleusercontent.com
google.client-secret=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
google.redirect-uri=http://localhost:5173/google/callback
google.token-uri=https://oauth2.googleapis.com/token
google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=TRACE
logging.level.reactor.netty.http.client=TRACE