spring.datasource.url=jdbc:mariadb://mewspaper-dev.cl8ygaiowfq8.ap-southeast-2.rds.amazonaws.com:3306/mewspaper?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8mb4&connectionCollation=utf8mb4_general_ci
spring.datasource.username=admin
spring.datasource.password=admin1234!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.pathmatch.matching-strategy=ant-path-matcher
server.port=8080

